language: python
install:
  - pip install coveralls

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev"

script: coverage run --source . -m py.test

after_success:
      coveralls

notifications:
  irc:
    channels:
      - "irc.drx.pl#pins"
    on_success: change
    on_failure: always
    skip_join: true
