language: python
install:
  - pip install coveralls

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev"
  - "nightly"

script: coverage run --source . -m py.test

after_success:
      coveralls
